# Generated by Django 4.2.4 on 2023-08-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnvironmentalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("humidity", models.IntegerField()),
                ("temperature", models.DecimalField(decimal_places=2, max_digits=5)),
                ("moisture", models.IntegerField()),
                ("timestamp", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
